# Generated by Django 4.2 on 2023-06-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='admins',
        ),
        migrations.DeleteModel(
            name='instructor',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
