# Generated by Django 4.2 on 2023-05-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_school_blog_semister_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="course_list",
            new_name="Semisters",
        ),
    ]
