# Generated by Django 4.2 on 2023-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_rename_course_list_department_semisters"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="semisters",
            field=models.ManyToManyField(to="mainapp.semister"),
        ),
    ]
