# Generated by Django 4.2 on 2023-06-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_school_semisters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semister',
            name='semister_number',
        ),
        migrations.AddField(
            model_name='semister',
            name='semister_name',
            field=models.CharField(default='semister X', max_length=100),
        ),
    ]
